services:
  mysql_hotel:
    image: mysql:8.0
    container_name: mysql_hotel
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  habitaciones_service:
    build: .
    container_name: habitaciones_service
    ports:
      - "8081:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@mysql_hotel:3306/${MYSQL_DB}
    depends_on:
      mysql_hotel:
        condition: service_healthy

volumes:
  mysql_data:
